use std::path::Path;
use std::time::Duration;

use hickory_resolver::TokioResolver;
use hickory_resolver::config::{ResolverConfig, ResolverOpts};
use hickory_resolver::net::runtime::TokioRuntimeProvider;
use hickory_resolver::system_conf::parse_resolv_conf;

pub fn build(path: &Path, timeout: Duration, retries: usize) -> TokioResolver {
    let parsed = std::fs::read(path)
        .map_err(|e| format!("read {}: {e}", path.display()))
        .and_then(|b| parse_resolv_conf(b).map_err(|e| format!("{}: {e}", path.display())));
    let (config, options) = match parsed {
        Ok(pair) => pair,
        Err(why) => {
            tracing::error!(
                reason = %why,
                "no usable upstream resolver; forwarded names get NXDOMAIN"
            );
            (
                ResolverConfig::from_parts(None, vec![], vec![]),
                ResolverOpts::default(),
            )
        }
    };
    let mut builder = TokioResolver::builder_with_config(config, TokioRuntimeProvider::default());
    *builder.options_mut() = options;
    builder.options_mut().timeout = timeout;
    builder.options_mut().attempts = retries;
    match builder.build() {
        Ok(r) => r,
        Err(e) => {
            tracing::error!(error = %e, "cannot build the upstream resolver; forwarding nothing");
            let mut empty = TokioResolver::builder_with_config(
                ResolverConfig::from_parts(None, vec![], vec![]),
                TokioRuntimeProvider::default(),
            );
            empty.options_mut().timeout = timeout;
            empty.options_mut().attempts = retries;
            empty
                .build()
                .expect("a resolver with no name servers always builds")
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::forward::{ForwardCfg, Forwarded, Forwarder};
    use hickory_proto::rr::{Name, RecordType};
    use std::str::FromStr;

    fn scratch(name: &str) -> std::path::PathBuf {
        let d =
            std::env::temp_dir().join(format!("edge-dns-upstream-{}-{name}", std::process::id()));
        std::fs::remove_dir_all(&d).ok();
        std::fs::create_dir_all(&d).unwrap();
        d
    }

    #[tokio::test]
    async fn unusable_resolv_conf_fails_fast() {
        let d = scratch("none");
        std::fs::write(d.join("empty"), "").unwrap();
        std::fs::write(d.join("comments"), "# generated by nothing\n").unwrap();
        std::fs::write(d.join("search-only"), "search cluster.local\n").unwrap();
        std::fs::write(d.join("garbage"), [0xffu8, 0xfe, 0x00, 0x01]).unwrap();
        std::fs::create_dir(d.join("dir")).unwrap();
        for f in [
            "missing",
            "empty",
            "comments",
            "search-only",
            "garbage",
            "dir",
        ] {
            let fwd = Forwarder::new(
                build(&d.join(f), Duration::from_millis(200), 0),
                ForwardCfg::default(),
            );
            let t = std::time::Instant::now();
            let got = fwd
                .forward(Name::from_str("example.com.").unwrap(), RecordType::A)
                .await;
            assert_eq!(got, Forwarded::Failed, "{f}");
            assert!(
                t.elapsed() < Duration::from_secs(2),
                "{f}: took {:?}",
                t.elapsed()
            );
        }
        std::fs::remove_dir_all(&d).ok();
    }

    #[tokio::test]
    async fn resolv_conf_timeout_overridden() {
        let d = scratch("real");
        std::fs::write(
            d.join("resolv.conf"),
            "nameserver 127.0.0.1\noptions timeout:9 attempts:5\n",
        )
        .unwrap();
        let fwd = Forwarder::new(
            build(&d.join("resolv.conf"), Duration::from_millis(200), 0),
            ForwardCfg::default(),
        );
        let got = fwd
            .forward(Name::from_str("example.com.").unwrap(), RecordType::A)
            .await;
        assert_eq!(got, Forwarded::Failed);
        std::fs::remove_dir_all(&d).ok();
    }
}
